### ISSUE TITLE
when NetDDE Client two server has the same RemoteName, it just save one server information to netddeclient.ini

### ISSUE THREAD

**Issue by chenvan** [chrisoldwood/NetDDE#1]
I set two server in NetDDEClient. they have same remote name,  but different server name and local name. 
But when I reopen the client, two server setting become exactly the same. not only remote name, but also server name and local name.  

it seems netddeclient.ini just save one server information when two server remote name is the same

![server](https://user-images.githubusercontent.com/7885757/142710649-2f147d8b-10ea-483a-988a-6bf3c6082814.png)

![serverError](https://user-images.githubusercontent.com/7885757/142710652-aa10e8e4-1c90-41e2-8fb0-30421c3d8e17.PNG)

![image](https://user-images.githubusercontent.com/7885757/142710755-113c8aba-132a-49ab-b6bf-58a6df9f2055.png)

**Comment by chrisoldwood** [comment]
Hey, thanks for the feedback!

It's been a _really long time_ since I used this 🙂 but I don't think should even be able to register two services on different hosts with the same name because the client wouldn't know which one to route requests to, or it would have to route the same request to all and work out which response to return, e.g. a wildcard query to list the supported topics.

I wonder what happens if you start two instances of Excel and open different workbooks? I'd have to refresh my memory on how multiple services works. Do _you_ know if multiple services with the same name should work?

**Comment by chenvan** [comment]
Sorry. English is not my first language. so I don't quite understand your question.
My situation is I have 10 remote computers. they all have application which is called "view". And I want to retrieve data from all of them.
Although their remote name are the same, but I gave them different local name. I use their local name to retrieve data. and they are work.
The problem is when I reopen netdde client. the setting become chaos.
I find the problem is the application use service's remote name as their service name to save. So when reopen netdde client, the setting become chaos. 
![142710755-113c8aba-132a-49ab-b6bf-58a6df9f2055](https://user-images.githubusercontent.com/7885757/144351589-0285f91d-19bb-4e42-bb3e-e8c48fd4a71f.png)

**Comment by chenvan** [comment]
I manually change netddeclient.ini. If they are save as the pic below. then netdde client setting would have no problem
![屏幕截图 2021-12-02 112611](https://user-images.githubusercontent.com/7885757/144352575-74f23373-292b-4fc8-beaa-21f454393e8b.png)

**Comment by chrisoldwood** [comment]
I've had a look at the code and there is no validation to stop you adding services with duplicate names which is another bug. I was going to suggest you run two separate instances using different folders for the configuration but I see that on start-up it pops-up the previous instance so that isn't a workaround either. It should be a fairly simple fix -- always use the local name for the config entry -- I just need to think about whether I need to bump the config file version too.

**Comment by chrisoldwood** [comment]
I've just started making some orthogonal changes to acclimatise myself with the code as it's been 20 years since I've really looked at it 🙂. When I scanned the `TODO.txt` it looks like I was aware of the problem but I guess it never caused me enough grief at the time:
> - Fix problems configuring two aliases for the same service (eg REUTER as REUTER1 & REUTER2)

**Comment by chrisoldwood** [comment]
I've fixed the config file issue although I still need to fix the UI to disallow the same local service name to be used multiple times:

![image](https://user-images.githubusercontent.com/2768826/157846580-06bc7946-13c4-4bdb-9085-b39fa66f4ac5.png)

I've uploaded an alpha ([NetDDE Bridge v2.5 Alpha](http://www.chrisoldwood.com/wip/netdde/netdde25alpha.zip)) with the current state of play to my home page so you can make use of this fixed version while I carry on fixing some other unrelated issues. Let me know if you spot any other problems and I'll put out a formal release in a few weeks.

---

Here is the config file now:
```
[Services]
Count=2
Service[0]=TEST1
Service[1]=TEST2

[TEST1]
RemoteName=EXCEL
LocalName=TEST1
Server=localhost
Port=8888
AsyncAdvises=False
TextOnly=False
InitialValue=#PNDG
FailedValue=#LINK
ReqInitValue=False

[TEST2]
RemoteName=EXCEL
LocalName=TEST2
Server=127.0.0.1
Port=8888
AsyncAdvises=False
TextOnly=False
InitialValue=#PNDG
FailedValue=#LINK
ReqInitValue=False
```

**Comment by chenvan** [comment]
thank you very much, I will download it later.

**Comment by chenvan** [comment]
I use [a javascript version DDE client](https://github.com/st-one-io/netdde) to communicate with new NetDDE Server. It breaks. I think it is maybe the javascript version's problem. But I think I should send you this feedback.

![屏幕截图 2022-03-13 193442](https://user-images.githubusercontent.com/7885757/158058527-e22f404e-62a3-4d83-9b8f-7236a2acddef.png)

**Comment by chrisoldwood** [comment]
Ah, thanks, I didn't even know this project existed 🙂. I've bumped compilers since `v2.0` was released way back in 2004 and the Unicode build is also the default now which may well be the source of the problem [1]. Naturally I can try mixing and matching the `v2.0` client with the newer `v2.5` server and see what happens (and vice-versa). Let me do that before mentioning it to ST-One as I'd lay good money on it being that the string wire format has unintentionally changed.

---

[1]  I had never envisaged anyone using the protocol directly and so assumed you'd be using `v2.5` on both ends. I guess I'll have to bump compatibility testing up the list 🙂.

**Comment by chrisoldwood** [comment]
As an aside the original bug you reported was in the NetDDE client, but you've just suggested you use a NodeJS client instead, or is that in addition to my client? (I'm just trying to understand a little more about how and why you're using it, for interest's sake.)

**Comment by chrisoldwood** [comment]
BTW I can reproduce using the `v2.0` client and `v2.5` server:
```
Unexpected exception caught in WinMain()

An error occured reading from a memory stream
```
Followed by a gazillion of these:
```
Unexpected exception caught in PopupWndProc()

Message: H=0x00040714 M=0x00000100 W=0x00000043 L=0x002E0001

Structured Exception: EXCEPTION_ACCESS_VIOLATION
```
So it looks like the error handling in the event loop has an issue too 🙂.

**Comment by chenvan** [comment]
> As an aside the original bug you reported was in the NetDDE client, but you've just suggested you use a NodeJS client instead, or is that in addition to my client? (I'm just trying to understand a little more about how and why you're using it, for interest's sake.)

You are so nice. 

For your question. At first. I want to use excel vba, NetDDE client, NetDDE server to build a monitor system. Soon I find NetDDE client bug, Inital Though cannot go on. Luckily I find the JS Version of NetDDE client. Also my javascript is much better than vba. So I switch it.

But my colleague only knows vba. He also wants to use NetDDE to build something. So I open this issue :)

**Comment by chrisoldwood** [comment]
Right, I've fixed all the serialization code so that it's now backwards compatible with my `v2.0` NetDDE client & server. I've uploaded another release to my home page ([NetDDE Bridge v2.5 Alpha 2](http://www.chrisoldwood.com/wip/netdde/netdde25alpha2.zip)) for you to try out.

Let me know how it goes. In the meantime I'm going to try and add some basic tests for that JavaScript based client you use as it looks interesting.

**Comment by chrisoldwood** [comment]
I've got a simple test in place now for that JS library which'll help raise awareness of it.

**Comment by chenvan** [comment]
> Right, I've fixed all the serialization code so that it's now backwards compatible with my `v2.0` NetDDE client & server. I've uploaded another release to my home page ([NetDDE Bridge v2.5 Alpha 2](http://www.chrisoldwood.com/wip/netdde/netdde25alpha2.zip)) for you to try out.
> 
> Let me know how it goes. In the meantime I'm going to try and add some basic tests for that JavaScript based client you use as it looks interesting.

the new version works well. thank you so much
